"description": "Pack action"
"inputs":
  "destination_dir":
    "description": "Destination directory"
    "required": true
  "image":
    "description": "Docker image"
    "required": true
  "source_dir":
    "description": "Action source directory"
    "required": true
"name": "Pack action"
"runs":
  "env":
    "DESTINATION_DIR": "${{ inputs.destination_dir }}"
    "IMAGE": "${{ inputs.image }}"
    "SOURCE_DIR": "${{ inputs.source_dir }}"
  "image": "docker://ghcr.io/pushcleat/action-pack-action:sha-9c562303c2b3ed43efcb6f280ff13613abbdb4ff"
  "using": "docker"
