"description": "Pack action"
"inputs":
  "destination_dir":
    "description": "Destination directory"
    "required": true
  "image":
    "description": "Docker image"
    "required": true
  "source_dir":
    "description": "Action source directory"
    "required": true
"name": "Pack action"
"runs":
  "env":
    "DESTINATION_DIR": "${{ inputs.destination_dir }}"
    "IMAGE": "${{ inputs.image }}"
    "SOURCE_DIR": "${{ inputs.source_dir }}"
  "image": "docker://docker.pkg.github.com/pushcleat/infrastructure/pack-action:sha-b9cc48a69d6cf278c9fe60f2144c9f84913c8955"
  "using": "docker"
