"description": "Pack action"
"inputs":
  "destination_dir":
    "description": "Destination directory"
    "required": true
  "image":
    "description": "Docker image"
    "required": true
  "source_dir":
    "description": "Action source directory"
    "required": true
"name": "Pack action"
"runs":
  "env":
    "DESTINATION_DIR": "${{ inputs.destination_dir }}"
    "IMAGE": "${{ inputs.image }}"
    "SOURCE_DIR": "${{ inputs.source_dir }}"
  "image": "docker://docker.pkg.github.com/pushcleat/infrastructure/pack-action:sha-8fe16e004ab3e31a3d2f7073939503a2cc58fc0e"
  "using": "docker"
