name: 'Pack action'
description: 'Pack action'
inputs:
  source_dir:
    description: 'Action source directory'
    required: true
  destination_dir:
    description: 'Destination directory'
    required: true
  image:
    description: 'Docker image'
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    SOURCE_DIR: ${{ inputs.source_dir }}
    DESTINATION_DIR: ${{ inputs.destination_dir }}
    IMAGE: ${{ inputs.image }}

