"description": "Pack action"
"inputs":
  "destination_dir":
    "description": "Destination directory"
    "required": true
  "image":
    "description": "Docker image"
    "required": true
  "source_dir":
    "description": "Action source directory"
    "required": true
"name": "Pack action"
"runs":
  "env":
    "DESTINATION_DIR": "${{ inputs.destination_dir }}"
    "IMAGE": "${{ inputs.image }}"
    "SOURCE_DIR": "${{ inputs.source_dir }}"
  "image": "docker://docker.pkg.github.com/pushcleat/action-pack-action/action-pack-action:sha-5bc149a5a5e009f14a62fd2ac01c89abc8754574"
  "using": "docker"
