images:
  - name: run
    description: Run
    provides:
      - ./entrypoint.sh
    image: pushcleat/pack-action:latest
    shell: bash
    before_script:
      - source .envrc
    containerRuntimeAccess: true
    cache:
    - name: home
      directory: /root/

  - name: test
    description: test
    provides:
      - bats
      - jsonnet
      - yq
    image: pushcleat/pack-action:test-latest
    shell: bash
    before_script:
      - source .envrc
    containerRuntimeAccess: true
    cache:
      - name: home
        directory: /root/
